jobs:
  build:
    executor:
      name: win/default
      shell: bash
    steps:
      - run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm64.tgz && tar -xvf ngrok-stable-linux-arm64.tgz && ./ngrok tcp 22
